# series_folder_crawler_v3.3.15.py
# Version 3.3.15
#
# Purpose:
# Scans a designated series folder for recorded media files (.ts) and their
# associated NextPVR EPG metadata (.xml) files. It attempts to match these
# local recordings to comprehensive episode metadata generated by
# Season_Episode_builder.py. The script outputs a structured JSON file
# (<series_slug>_Processed.json) that maps local files to their corresponding
# episode metadata, including data from all configured metadata providers.
# This output is intended for consumption by file_organizer.py for renaming,
# moving, and NFO file creation.
#
# Conventions:
# - Configuration is read from 'config/paths.txt'.
# - Processed JSON output is stored in 'data/<series_slug>/'.
# - Logs are stored in 'logs/<series_slug>/'.
# - Thresholds for matching are configured in the '[thresholds]' section of paths.txt,
#   using keys like 'passX_threshold_Series_Name' (casing-sensitive for Series_Name).
#
# Change Log:
# [3.3.15] - 2025-05-23
# - Enhanced `normalize` function to consistently handle " and " vs. " & " variations.
#   It now replaces " and " with " & " (or similar logic) before other punctuation removal,
#   allowing for more robust exact matches in Pass 1.
# - Updated versioning.
# [3.3.14] - 2025-05-23
# - Fixed the `find_related_ts_files` function: Corrected the logic for matching
#   .ts file basenames to .xml basenames, resolving the `size: 0` issue and
#   ensuring .ts files are correctly identified and their sizes captured.
# - Refined `logical_base_name` derivation to consistently handle `-0` suffixes.
# - Updated versioning.
# [3.3.13] - 2025-05-23
# - Added extensive `print` statements for debugging silent failures, especially
#   during logger setup and path loading.
# - Implemented a fallback `StreamHandler` for the logger in `setup_logger`
#   to ensure console output if file logging fails.
# - Enhanced `except` block in `__main__` to ensure console error output.
# - Updated versioning.
# [3.3.12] - 2025-05-23
# - General code cleanup and enhanced commenting to align with project conventions.
# - Ensured no hardcoded values (except for relative paths to 'config', 'data', and 'logs').
# - Updated the changelog to reflect this version.
# - Confirmed adherence to the principles outlined in planning documents,
#   especially regarding the inclusion of full provider metadata in the output.
# [3.3.11] - 2025-05-22
# - Fixed ValueError: 'Series name not found in paths.txt' by ensuring correct casing
#   for threshold lookups in paths.txt. Introduced `series_config_key_slug` to match
#   the 'Ax_Men' pattern in the config file, while `series_folder_slug` (lowercase)
#   is used for file system paths.
# - Refined logger initialization flow: `load_paths` now fully sets up the logger
#   after all necessary path variables are determined, removing redundant initial call.
# - Updated versioning.
# [3.3.10] - 2025-05-22
# - Fixed ValueError: 'Series name not found in paths.txt' by correcting ConfigParser
#   section names to match user's paths.txt: changed 'series_paths' to 'series'
#   and 'matching_thresholds' to 'thresholds'.
# - Updated versioning.
# [3.3.9] - 2025-05-22
# - Fixed NameError: name 'ConfigParser' is not defined by adding 'from configparser import ConfigParser' import.
# - Updated versioning.
# [3.3.8] - 2025-05-22
# - Fixed FileNotFoundError for 'paths.txt' by correctly pointing to 'config/paths.txt'.
# - Ensured output JSON (series_name_Processed.json) is written to the series-specific
#   subdirectory within the 'data' folder, as defined by JSON_FOLDER.
# - Added extensive comments to explain current script logic and global variables.
# - Updated versioning.
# [3.3.7] - 2025-04-29
# - Fixed title extraction in build_match_pool: Removed ep.get("title", "") to use only titles dictionary, preventing empty title mismatches.
# - Enhanced normalize to remove all punctuation for robust case-insensitive matching.
# - Integrated unmatched episodes into matches output with basenames, eliminated pending section.
# - Grouped .ts files by .xml basename in output.
# - Improved logging for .xml subtitle and match failures.
# - Prioritized tvmaze titles in Pass 1 matching.
# - Fixed syntax error in load_series_metadata (missing quote in encoding="utf-8").
# - Fixed syntax error in match_group_to_provider (malformed f-string in Pass 2 logging).

import os
import sys
import json
import xml.etree.ElementTree as ET
import re
import unicodedata
from datetime import datetime
from difflib import SequenceMatcher
from collections import defaultdict
import logging
from configparser import ConfigParser

# ------------------
# Global Variables
# ------------------
SERIES_NAME = None         # The name of the TV series being processed (e.g., "Ax Men")
SERIES_FOLDER_SLUG = None  # Lowercase, underscore-separated slug for folder/file names (e.g., "ax_men")
ROOT_FOLDER = ""           # The root directory where the series' recorded files are stored
METADATA_JSON = ""         # Path to the comprehensive metadata JSON generated by Season_Episode_builder.py
OUTPUT_JSON = ""           # Path where the processed output JSON will be saved
JSON_FOLDER = "data"       # Base directory for JSON output (relative to script)
LOG_PATH = "logs"          # Base directory for log files (relative to script)
PASS4_THRESHOLD = 12       # Default threshold for token overlap in Pass 4 matching
PASS2_THRESHOLD = 0.80     # Default similarity ratio threshold for fuzzy title matching in Pass 2
PASS3_THRESHOLD = 0.80     # Default similarity ratio threshold for sliding window matching in Pass 3

# ------------------
# Logging Setup
# ------------------
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

def setup_logger(series_slug: str, log_base_path: str):
    """
    Sets up the file handler for the logger, directing logs to a series-specific file.
    Includes a fallback to console logging if file logging cannot be initialized.
    """
    print(f"DEBUG: Entering setup_logger for {series_slug} at {log_base_path}")
    log_dir = os.path.join(log_base_path, series_slug)
    
    try:
        os.makedirs(log_dir, exist_ok=True)
        print(f"DEBUG: Log directory ensured: {log_dir}")
    except Exception as e:
        print(f"ERROR: Could not create log directory {log_dir}: {e}", file=sys.stderr)
        console_handler = logging.StreamHandler(sys.stdout)
        formatter = logging.Formatter("[%(asctime)s] [%(levelname)s] %(message)s")
        console_handler.setFormatter(formatter)
        logger.addHandler(console_handler)
        logger.error(f"Failed to create log directory: {e}. Logging to console only.")
        return

    if logger.handlers:
        for handler in logger.handlers:
            logger.removeHandler(handler)
            handler.close()

    log_file_path = os.path.join(log_dir, f"series_folder_crawler_{series_slug}.log")
    try:
        file_handler = logging.FileHandler(log_file_path, mode="a", encoding="utf-8")
        formatter = logging.Formatter("[%(asctime)s] [%(levelname)s] %(message)s")
        file_handler.setFormatter(formatter)
        logger.addHandler(file_handler)
        print(f"DEBUG: File handler added for {log_file_path}")
        logger.info(f"series_folder_crawler_v3.3.15 starting for {SERIES_NAME}")
    except Exception as e:
        print(f"ERROR: Failed to set up file logger at {log_file_path}: {e}", file=sys.stderr)
        console_handler = logging.StreamHandler(sys.stdout)
        console_handler.setFormatter(formatter)
        logger.addHandler(console_handler)
        logger.error(f"Failed to set up file logger: {e}. Logging to console.")


# ------------------
# Text Processing Utilities
# ------------------

def normalize(s: str) -> str:
    """
    Normalizes a string for comparison by:
    1. Lowercasing.
    2. Replacing " and " with " & ".
    3. Removing all other non-alphanumeric characters (except whitespace).
    4. Stripping leading/trailing whitespace.
    5. Applying Unicode normalization.
    """
    if not s:
        return ""
    
    # Step 1: Lowercase
    s = s.lower()
    
    # Step 2: Replace " and " with " & " for consistent matching
    s = s.replace(" and ", " & ")
    
    # Step 3: Remove all other punctuation and non-alphanumeric characters (keep spaces)
    s = re.sub(r"[^\w\s&]", "", s) # Keep word characters, whitespace, and the '&'
    
    # Step 4 & 5: Strip whitespace and apply Unicode normalization
    return unicodedata.normalize("NFC", s).strip()

# ------------------
# Configuration Loading
# ------------------

def load_paths(series_name: str):
    """
    Loads configuration paths and matching thresholds from 'config/paths.txt'.
    """
    global ROOT_FOLDER, METADATA_JSON, OUTPUT_JSON, LOG_PATH, \
           PASS4_THRESHOLD, PASS2_THRESHOLD, PASS3_THRESHOLD, SERIES_NAME, SERIES_FOLDER_SLUG

    SERIES_NAME = series_name
    SERIES_FOLDER_SLUG = SERIES_NAME.lower().replace(" ", "_").replace("'", "")

    config_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "config", "paths.txt")
    if not os.path.exists(config_path):
        config_path = os.path.join("config", "paths.txt")
        if not os.path.exists(config_path):
            sys.stderr.write(f"ERROR: Configuration file not found at: {config_path}\n")
            raise FileNotFoundError(f"paths.txt not found at {config_path}")

    config_parser = ConfigParser()
    config_parser.read(config_path)

    LOG_PATH = config_parser.get("general", "LOG_PATH", fallback=LOG_PATH)
    
    setup_logger(SERIES_FOLDER_SLUG, LOG_PATH)
    logger.info(f"Loaded configuration from: {config_path}")

    found_series_config = False
    for i in range(1, 50):
        series_key = f"series_name_{i}"
        if config_parser.has_option("series", series_key) and \
           config_parser.get("series", series_key).strip('"') == series_name:

            ROOT_FOLDER = config_parser.get("series", f"series_path_{i}", fallback="")
            METADATA_JSON = os.path.join(JSON_FOLDER, SERIES_FOLDER_SLUG, f"{series_name}.json")
            OUTPUT_JSON = os.path.join(JSON_FOLDER, SERIES_FOLDER_SLUG, f"{series_name.replace(' ', '_')}_Processed.json")

            series_config_key_slug = series_name.replace(" ", "_").replace("'", "")
            PASS4_THRESHOLD = int(config_parser.get("thresholds", f"pass4_threshold_{series_config_key_slug}", fallback=str(PASS4_THRESHOLD)))
            PASS2_THRESHOLD = float(config_parser.get("thresholds", f"pass2_threshold_{series_config_key_slug}", fallback=str(PASS2_THRESHOLD)))
            PASS3_THRESHOLD = float(config_parser.get("thresholds", f"pass3_threshold_{series_config_key_slug}", fallback=str(PASS3_THRESHOLD)))

            found_series_config = True
            logger.info(f"Configuration loaded for series '{series_name}':")
            logger.info(f"  ROOT_FOLDER: {ROOT_FOLDER}")
            logger.info(f"  METADATA_JSON: {METADATA_JSON}")
            logger.info(f"  OUTPUT_JSON: {OUTPUT_JSON}")
            logger.info(f"  PASS2_THRESHOLD: {PASS2_THRESHOLD}")
            logger.info(f"  PASS3_THRESHOLD: {PASS3_THRESHOLD}")
            logger.info(f"  PASS4_THRESHOLD: {PASS4_THRESHOLD}")
            return

    if not found_series_config:
        logger.error(f"Series name '{series_name}' not found in 'series' section of paths.txt.")
        raise ValueError(f"Series name '{series_name}' not found in paths.txt.")

# ------------------
# Local File Scanning
# ------------------

def scan_xml_metadata() -> dict:
    """
    Scans ROOT_FOLDER for .xml files, extracts subtitle and description,
    and groups XML files by these normalized values.
    """
    epg_groups = defaultdict(list)
    logger.info(f"Scanning XML metadata in: {ROOT_FOLDER}")
    
    if not os.path.isdir(ROOT_FOLDER):
        logger.error(f"ROOT_FOLDER '{ROOT_FOLDER}' is not a valid directory or does not exist. Cannot scan XML metadata.")
        return epg_groups

    for file in os.listdir(ROOT_FOLDER):
        if file.endswith(".xml") and os.path.getsize(os.path.join(ROOT_FOLDER, file)) > 0:
            full_path = os.path.join(ROOT_FOLDER, file)
            try:
                tree = ET.parse(full_path)
                root = tree.getroot()
                subtitle = root.findtext("subtitle", "")
                description = root.findtext("description", "")
                normalized_subtitle = normalize(subtitle)
                normalized_description = normalize(description)
                key = (normalized_subtitle, normalized_description)
                epg_groups[key].append(file)
                logger.debug(f"Scanned XML: {file}, subtitle='{normalized_subtitle[:50]}...', description='{normalized_description[:50]}...'")
            except ET.ParseError as e:
                logger.warning(f"XML Parse Error: {file} - {e}. Skipping file.")
            except Exception as e:
                logger.error(f"Error scanning XML file {file}: {e}", exc_info=True)
    logger.info(f"Found {len(epg_groups)} unique XML subtitle/description groups.")
    return epg_groups

def find_related_ts_files(xml_basenames: set) -> dict:
    """
    Scans ROOT_FOLDER for .ts files and groups them by their base filename,
    only including those with a corresponding .xml file.
    """
    groups = defaultdict(list)
    logger.info(f"Finding related .ts files in: {ROOT_FOLDER}")
    
    if not os.path.isdir(ROOT_FOLDER):
        logger.error(f"ROOT_FOLDER '{ROOT_FOLDER}' is not a valid directory or does not exist. Cannot find related .ts files.")
        return groups

    for file in os.listdir(ROOT_FOLDER):
        if not file.endswith(".ts"):
            continue
        
        ts_base_name = os.path.splitext(file)[0] 
        # Remove trailing '-0' or '-0-0' from the .ts basename to match the XML's logical basename
        logical_base_name = re.sub(r"(-0)+$", "", ts_base_name) 

        full_path = os.path.join(ROOT_FOLDER, file)
        
        # Check if the logical_base_name exists in the set of XML basenames.
        if logical_base_name in xml_basenames:
            groups[logical_base_name].append({
                "path": full_path.replace("\\", "/"),
                "size": os.path.getsize(full_path),
                "broken": "-0" in file
            })
            logger.debug(f"Found related .ts file: {file} for logical basename {logical_base_name}")
        else:
            logger.debug(f"Skipping .ts file {file}: No matching XML basename '{logical_base_name}' found in EPG data.")

    logger.info(f"Found {len(groups)} groups of related .ts files.")
    return groups

# ------------------
# Provider Metadata Processing
# ------------------

def load_series_metadata() -> dict:
    """
    Loads the comprehensive series metadata JSON generated by Season_Episode_builder.py.
    """
    if not os.path.exists(METADATA_JSON):
        logger.error(f"Metadata JSON not found: {METADATA_JSON}. Run Season_Episode_builder.py first.")
        raise FileNotFoundError(f"Metadata JSON not found: {METADATA_JSON}")
    logger.info(f"Loading series metadata from: {METADATA_JSON}")
    try:
        with open(METADATA_JSON, "r", encoding="utf-8") as f:
            metadata = json.load(f)
        logger.info("Series metadata loaded successfully.")
        return metadata
    except json.JSONDecodeError as e:
        logger.error(f"Error decoding metadata JSON: {e}", exc_info=True)
        raise
    except Exception as e:
        logger.error(f"Error loading series metadata: {e}", exc_info=True)
        raise

def build_match_pool(meta: dict) -> list:
    """
    Builds a pool of episodes from the loaded metadata for matching.
    Each entry contains normalized titles and overviews from all providers.
    """
    pool = []
    seen_keys = set()
    logger.info("Building match pool from provider metadata.")
    for season in meta.get("seasons", []):
        season_num = season.get("season_number")
        if season_num is None:
            logger.warning(f"Skipping season with missing 'season_number': {season}")
            continue
        for ep in season.get("episodes", []):
            episode_num = ep.get("episode_number")
            if episode_num is None:
                logger.warning(f"Skipping episode with missing 'episode_number': S{season_num} - {ep}")
                continue
            ep_key = (season_num, str(episode_num))
            if ep_key in seen_keys:
                logger.warning(f"Duplicate episode key found: S{season_num}E{episode_num}. Skipping.")
                continue
            seen_keys.add(ep_key)
            normalized_titles = [
                normalize(t) for t in ep.get("titles", {}).values()
                if t and "episode" not in t.lower()
            ]
            normalized_overviews = [
                normalize(o) for o in ep.get("overviews", {}).values() if o
            ]

            pool.append({
                "season": season_num,
                "episode": episode_num,
                "titles": normalized_titles,
                "overviews": normalized_overviews,
                "original_title": ep.get("titles", {}).get("tvmaze", ""),
                "air_date": ep.get("air_date", {}).get("tvmaze", "")
            })
            logger.debug(f"Added to match pool: S{season_num}E{episode_num}, titles={normalized_titles[:3]}, overviews={normalized_overviews[:1]}")
    logger.info(f"Match pool built with {len(pool)} entries.")
    return pool

# ------------------
# Matching Logic
# ------------------

def slide_window(text: str, size: int = 10) -> list:
    """
    Generates sliding window snippets from a given text.
    Used for Pass 3 to find matches within longer descriptions.
    """
    words = text.split()
    return [' '.join(words[i:i+size]) for i in range(len(words) - size + 1)]

def token_overlap(text1: str, text2: str) -> int:
    """
    Calculates the number of overlapping unique tokens (words) between two texts.
    Used for Pass 4 for a different type of description similarity.
    """
    set1 = set(text1.split())
    set2 = set(text2.split())
    return len(set1.intersection(set2))

def match_group_to_provider(subtitle: str, desc: str, match_pool: list, pass_num: int):
    """
    Attempts to match a local XML subtitle/description pair to an episode in the match_pool
    using a multi-pass strategy.
    Returns the index of the matched episode in the pool and the matched episode dictionary,
    or (None, None) if no match is found.
    """
    logger.debug(f"Pass {pass_num}: Processing local subtitle='{subtitle}', pool size={len(match_pool)}")
    
    key_sub = normalize(subtitle)
    key_desc = normalize(desc)
    words_in_desc = key_desc.split()

    # Pass 1: Exact Subtitle Match (with tvmaze preference)
    if pass_num == 1:
        for i, m in enumerate(match_pool):
            # Prioritize matching against the 'original_title' (which is tvmaze's title)
            if m["original_title"] and key_sub == normalize(m["original_title"]):
                logger.info(f"Pass 1: Matched subtitle='{key_sub}' to TVMaze title='{m['original_title']}', S{m['season']}E{m['episode']}")
                return i, m
            # Then check all other normalized titles
            if key_sub in m["titles"]:
                logger.info(f"Pass 1: Matched subtitle='{key_sub}' to title in pool, S{m['season']}E{m['episode']}")
                return i, m
        logger.debug(f"Pass 1: No exact match for subtitle='{key_sub}'")
        return None, None

    # Pass 2: Fuzzy Subtitle Match
    elif pass_num == 2:
        for i, m in enumerate(match_pool):
            # Check against all normalized titles in the pool entry
            for title_in_pool in m["titles"]:
                if title_in_pool and SequenceMatcher(None, key_sub, title_in_pool).ratio() >= PASS2_THRESHOLD:
                    logger.info(f"Pass 2: Matched subtitle='{key_sub}' to '{title_in_pool}', S{m['season']}E{m['episode']} (ratio={SequenceMatcher(None, key_sub, title_in_pool).ratio():.2f})")
                    return i, m
        logger.debug(f"Pass 2: No fuzzy subtitle match for '{key_sub}' (threshold={PASS2_THRESHOLD})")
        return None, None

    # Pass 3: Sliding Window Description Match
    elif pass_num == 3 and len(words_in_desc) >= 10: # Only run if description is long enough for snippets
        snippets = slide_window(key_desc)
        for i, m in enumerate(match_pool):
            for overview_in_pool in m["overviews"]:
                for snippet in snippets:
                    ratio = SequenceMatcher(None, snippet, overview_in_pool).ratio()
                    if ratio >= PASS3_THRESHOLD:
                        logger.info(f"Pass 3: Matched snippet='{snippet[:30]}...' to overview='{overview_in_pool[:30]}...', S{m['season']}E{m['episode']} (ratio={ratio:.2f})")
                        return i, m
        logger.debug(f"Pass 3: No sliding window match for description='{key_desc[:50]}...' (threshold={PASS3_THRESHOLD})")
        return None, None

    # Pass 4: Token Overlap Description Match with Subtitle Ratio Check
    elif pass_num == 4:
        for i, m in enumerate(match_pool):
            for overview_in_pool in m["overviews"]:
                overlap = token_overlap(key_desc, overview_in_pool)
                if overlap >= PASS4_THRESHOLD:
                    # Additional check: ensure subtitle similarity is not too low
                    max_subtitle_ratio = 0
                    if m["titles"]:
                        max_subtitle_ratio = max([SequenceMatcher(None, key_sub, t).ratio() for t in m["titles"]])

                    # Stricter rules for Season 0 (specials) matches
                    if m["season"] == 0:
                        if max_subtitle_ratio < 0.90: # Require very high subtitle match for specials
                            logger.debug(f"Pass 4: Rejected Season 0 match for '{key_sub}' (S{m['season']}E{m['episode']}) due to low subtitle ratio ({max_subtitle_ratio:.2f})")
                            continue
                    elif max_subtitle_ratio < 0.60: # General subtitle match threshold for non-specials
                        logger.debug(f"Pass 4: Rejected match for '{key_sub}' (S{m['season']}E{m['episode']}) due to low subtitle ratio ({max_subtitle_ratio:.2f})")
                        continue
                    
                    logger.info(f"Pass 4: Matched description='{key_desc[:50]}...' to overview='{overview_in_pool[:50]}...', S{m['season']}E{m['episode']} (overlap={overlap}, subtitle_ratio={max_subtitle_ratio:.2f})")
                    return i, m
        logger.debug(f"Pass 4: No token overlap match for description='{key_desc[:50]}...' (threshold={PASS4_THRESHOLD})")
        return None, None

    logger.info(f"Final: No match found after all passes for subtitle='{key_sub}', description='{key_desc[:50]}...'")
    return None, None

def build_episode_groups() -> dict:
    """
    Orchestrates the crawling, metadata loading, and matching process.
    Produces the final structured JSON output mapping local files to matched episodes.
    """
    print("DEBUG: Entering build_episode_groups.")
    epg_data = scan_xml_metadata()
    print(f"DEBUG: scan_xml_metadata completed. Found {len(epg_data)} EPG groups.")
    
    provider_meta = load_series_metadata()
    print(f"DEBUG: load_series_metadata completed. Contains {len(provider_meta.get('seasons', []))} seasons.")
    
    match_pool = build_match_pool(provider_meta)
    print(f"DEBUG: build_match_pool completed. Pool size: {len(match_pool)}.")

    results = {"series_name": SERIES_NAME, "seasons": []}
    
    all_xml_basenames = set(os.path.splitext(f)[0] for group_list in epg_data.values() for f in group_list)
    ts_groups = find_related_ts_files(all_xml_basenames)
    print(f"DEBUG: find_related_ts_files completed. Found {len(ts_groups)} .ts groups.")

    unmatched_epg_pairs = [(subtitle, desc, xml_list) for (subtitle, desc), xml_list in epg_data.items()]
    
    temp_matched_episodes = defaultdict(list)
    
    logger.info(f"Starting matching process with {len(unmatched_epg_pairs)} local EPG pairs and {len(match_pool)} provider episodes.")

    for pass_num in range(1, 5):
        logger.info(f"--- Starting Pass {pass_num} ---")
        current_pass_unmatched = []
        current_match_pool_for_pass = match_pool[:]

        for subtitle, desc, xml_list in unmatched_epg_pairs:
            index, matched_provider_episode = match_group_to_provider(subtitle, desc, current_match_pool_for_pass, pass_num)
            
            if matched_provider_episode and index is not None:
                logger.info(f"Match found in Pass {pass_num}: Local '{subtitle[:50]}...' matched to S{matched_provider_episode['season']}E{matched_provider_episode['episode']} ('{matched_provider_episode['original_title']}')")
                
                group_data = {
                    "local_xml_subtitle": subtitle,
                    "local_xml_description": desc,
                    "matched_season": matched_provider_episode["season"],
                    "matched_episode": matched_provider_episode["episode"],
                    "matched_by_pass": pass_num,
                    "provider_metadata": {
                        "titles": matched_provider_episode["titles"],
                        "overviews": matched_provider_episode["overviews"],
                        "ids": matched_provider_episode.get("ids", {}),
                        "air_date": matched_provider_episode.get("air_date", {}),
                        "synthetic": matched_provider_episode.get("synthetic", False)
                    },
                    "files": []
                }

                for xml_file in xml_list:
                    basename = os.path.splitext(xml_file)[0]
                    logical_basename_for_xml = re.sub(r"(-0)+$", "", basename) 
                    related_ts = ts_groups.get(logical_basename_for_xml, [])
                    if related_ts:
                        group_data["files"].extend(related_ts)
                    else:
                        group_data["files"].append({
                            "path": os.path.join(ROOT_FOLDER, f"{basename}.ts").replace("\\", "/"),
                            "size": 0,
                            "broken": False,
                            "note": "No .ts file found for this XML basename"
                        })
                
                temp_matched_episodes[(matched_provider_episode["season"], matched_provider_episode["episode"])].append(group_data)
                
                if matched_provider_episode in match_pool:
                    match_pool.remove(matched_provider_episode)
                    logger.debug(f"Removed S{matched_provider_episode['season']}E{matched_provider_episode['episode']} from match_pool. New size: {len(match_pool)}")
                else:
                    logger.debug(f"S{matched_provider_episode['season']}E{matched_provider_episode['episode']} already removed from match_pool.")

            else:
                current_pass_unmatched.append((subtitle, desc, xml_list))
        
        unmatched_epg_pairs = current_pass_unmatched
        logger.info(f"Pass {pass_num} completed. {len(unmatched_epg_pairs)} pairs remaining unmatched.")
        
        if not unmatched_epg_pairs:
            logger.info("All local EPG pairs matched. Ending matching process early.")
            break

    print("DEBUG: Finalizing results.")
    for (season_num, episode_num), matched_groups in temp_matched_episodes.items():
        target_season = next((s for s in results["seasons"] if s["season_number"] == season_num), None)
        if not target_season:
            target_season = {"season_number": season_num, "episodes": []}
            results["seasons"].append(target_season)
        
        first_group = matched_groups[0]
        episode_entry = {
            "episode_number": episode_num,
            "local_xml_subtitle": first_group["local_xml_subtitle"],
            "local_xml_description": first_group["local_xml_description"],
            "matched_by_pass": first_group["matched_by_pass"],
            "titles": first_group["provider_metadata"]["titles"],
            "overviews": first_group["provider_metadata"]["overviews"],
            "ids": first_group["provider_metadata"]["ids"],
            "air_date": first_group["provider_metadata"]["air_date"],
            "synthetic": first_group["provider_metadata"].get("synthetic", False),
            "files": []
        }
        
        for group in matched_groups:
            episode_entry["files"].extend(group["files"])
        
        target_season["episodes"].append(episode_entry)

    results["seasons"].sort(key=lambda x: x["season_number"])
    for season in results["seasons"]:
        season["episodes"].sort(key=lambda x: x["episode_number"])

    if unmatched_epg_pairs:
        logger.info(f"Found {len(unmatched_epg_pairs)} local EPG pairs that could not be matched to provider metadata.")
        unmatched_season = {"season_number": "unmatched", "episodes": []}
        
        unmatched_episode_counter = 1
        for subtitle, desc, xml_list in unmatched_epg_pairs:
            unmatched_entry = {
                "episode_number": unmatched_episode_counter,
                "local_xml_subtitle": subtitle,
                "local_xml_description": desc,
                "files": [],
                "reason": "No match found in provider metadata"
            }
            for xml_file in xml_list:
                basename = os.path.splitext(xml_file)[0]
                logical_basename_for_xml = re.sub(r"(-0)+$", "", basename)
                related_ts = ts_groups.get(logical_basename_for_xml, [])
                if related_ts:
                    unmatched_entry["files"].extend(related_ts)
                else:
                    unmatched_entry["files"].append({
                        "path": os.path.join(ROOT_FOLDER, f"{basename}.ts").replace("\\", "/"),
                        "size": 0,
                        "broken": False,
                        "note": "No .ts file found for this XML basename"
                    })
            unmatched_season["episodes"].append(unmatched_entry)
            unmatched_episode_counter += 1
        
        results["seasons"].append(unmatched_season)
        results["seasons"].sort(key=lambda x: x["season_number"] if isinstance(x["season_number"], int) else float('inf'))

    logger.info(f"Matching process complete. Total seasons in output: {len(results['seasons'])}")
    print("DEBUG: build_episode_groups function finished.")
    return results

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python scripts/series_folder_crawler.py \"Series Name\"")
        sys.exit(1)

    SERIES_NAME_ARG = sys.argv[1]
    
    print(f"DEBUG: Script execution started for '{SERIES_NAME_ARG}'")

    try:
        load_paths(SERIES_NAME_ARG)
        print(f"DEBUG: load_paths completed. ROOT_FOLDER: {ROOT_FOLDER}")
        
        grouped = build_episode_groups()
        print("DEBUG: build_episode_groups call completed.")
        
        output_dir = os.path.dirname(OUTPUT_JSON)
        os.makedirs(output_dir, exist_ok=True)
        print(f"DEBUG: Output directory ensured: {output_dir}")

        with open(OUTPUT_JSON, "w", encoding="utf-8") as f:
            json.dump(grouped, f, indent=2)
        logger.info(f"Finished. Output saved to {OUTPUT_JSON}")
        print(f"DEBUG: Output written to {OUTPUT_JSON}")
    except Exception as e:
        logger.exception(f"An unhandled error occurred during script execution for '{SERIES_NAME_ARG}': {e}")
        print(f"ERROR: An unhandled error occurred: {e}", file=sys.stderr)
        sys.exit(1)

