# series_folder_crawler_v3.3.10.py
# Version 3.3.10
# Scans a series folder for recorded media files (.ts) and their associated metadata (.xml).
# It attempts to match this local EPG data to comprehensive provider metadata
# generated by Season_Episode_builder.py. The goal is to produce a structured JSON
# output that maps local files to known episodes for later renaming and organization.
#
# Change Log:
# [3.3.10] - 2025-05-22
# - Fixed ValueError: 'Series name not found in paths.txt' by correcting ConfigParser
#   section names to match user's paths.txt: changed 'series_paths' to 'series'
#   and 'matching_thresholds' to 'thresholds'.
# - Updated versioning.
# [3.3.9] - 2025-05-22
# - Fixed NameError: name 'ConfigParser' is not defined by adding 'from configparser import ConfigParser' import.
# - Updated versioning.
# [3.3.8] - 2025-05-22
# - Fixed FileNotFoundError for 'paths.txt' by correctly pointing to 'config/paths.txt'.
# - Ensured output JSON (series_name_Processed.json) is written to the series-specific
#   subdirectory within the 'data' folder, as defined by JSON_FOLDER.
# - Added extensive comments to explain current script logic and global variables.
# - Updated versioning.
# [3.3.7] - 2025-04-29
# - Fixed title extraction in build_match_pool: Removed ep.get("title", "") to use only titles dictionary, preventing empty title mismatches.
# - Enhanced normalize to remove all punctuation for robust case-insensitive matching.
# - Integrated unmatched episodes into matches output with basenames, eliminated pending section.
# - Grouped .ts files by .xml basename in output.
# - Improved logging for .xml subtitle and match failures.
# - Prioritized tvmaze titles in Pass 1 matching.
# - Fixed syntax error in load_series_metadata (missing quote in encoding="utf-8").
# - Fixed syntax error in match_group_to_provider (malformed f-string in Pass 2 logging).

import os
import sys
import json
import xml.etree.ElementTree as ET
import re
import unicodedata
from datetime import datetime
from difflib import SequenceMatcher
from collections import defaultdict
import logging # Import standard logging module
from configparser import ConfigParser # Import ConfigParser

# ------------------
# Global Variables
# ------------------
# These global variables store configuration and paths, populated by load_paths().
SERIES_NAME = None         # The name of the TV series being processed (e.g., "Ax Men")
ROOT_FOLDER = ""           # The root directory where the series' recorded files are stored
METADATA_JSON = ""         # Path to the comprehensive metadata JSON generated by Season_Episode_builder.py
OUTPUT_JSON = ""           # Path where the processed output JSON (mapping local files to episodes) will be saved
JSON_FOLDER = ""           # Base directory for JSON output (e.g., "data")
LOG_PATH = ""              # Base directory for log files (e.g., "logs")
PASS4_THRESHOLD = 12       # Threshold for token overlap in Pass 4 matching
PASS2_THRESHOLD = 0.80     # Similarity ratio threshold for fuzzy title matching in Pass 2
PASS3_THRESHOLD = 0.80     # Similarity ratio threshold for sliding window matching in Pass 3

# ------------------
# Logging Setup
# ------------------
# Use standard Python logging for consistency and better control.
# This logger will write to a file specific to the series being processed.
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG) # Set to DEBUG for detailed output during development
file_handler = None # Will be initialized in load_paths

def setup_logger(series_slug: str, log_base_path: str):
    """
    Sets up the file handler for the logger, ensuring logs go to the correct series-specific file.
    This function is called once after SERIES_NAME and LOG_PATH are determined.
    """
    global file_handler
    log_dir = os.path.join(log_base_path, series_slug)
    os.makedirs(log_dir, exist_ok=True) # Ensure log directory exists

    # Remove existing handlers to prevent duplicate log entries on re-runs
    if logger.handlers:
        for handler in logger.handlers:
            logger.removeHandler(handler)
            handler.close() # Close the file handler to release the file lock

    file_handler = logging.FileHandler(os.path.join(log_dir, f"series_folder_crawler_{series_slug}.log"), mode="a", encoding="utf-8")
    formatter = logging.Formatter("[%(asctime)s] [%(levelname)s] %(message)s")
    file_handler.setFormatter(formatter)
    logger.addHandler(file_handler)
    logger.info(f"series_folder_crawler_v3.3.10 starting for {SERIES_NAME}")


# ------------------
# Text Processing Utilities
# ------------------

def normalize(s: str) -> str:
    """
    Normalizes a string for comparison: removes punctuation, converts to lowercase,
    strips whitespace, and applies Unicode normalization (NFC).
    """
    if not s:
        return ""
    # Remove all punctuation and normalize Unicode characters
    s = re.sub(r"[^\w\s]", "", s) # Keep only word characters (alphanumeric + underscore) and whitespace
    return unicodedata.normalize("NFC", s).strip().lower()

# ------------------
# Configuration Loading
# ------------------

def load_paths(series_name: str):
    """
    Loads configuration paths and thresholds from paths.txt.
    This function expects paths.txt to be in the 'config' subdirectory
    relative to where the script is executed.
    """
    global ROOT_FOLDER, METADATA_JSON, OUTPUT_JSON, JSON_FOLDER, LOG_PATH, \
           PASS4_THRESHOLD, PASS2_THRESHOLD, PASS3_THRESHOLD, SERIES_NAME

    SERIES_NAME = series_name # Set global SERIES_NAME early for logging

    config_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "config", "paths.txt")
    
    # Fallback if the above path doesn't work (e.g., running from project root)
    if not os.path.exists(config_path):
        config_path = os.path.join("config", "paths.txt")

    if not os.path.exists(config_path):
        logger.error(f"Configuration file not found at expected path: {config_path}")
        raise FileNotFoundError(f"paths.txt not found at {config_path}")

    config_parser = ConfigParser()
    config_parser.read(config_path)

    # Extract general paths
    JSON_FOLDER = config_parser.get("general", "JSON_FOLDER", fallback="data")
    LOG_PATH = config_parser.get("general", "LOG_PATH", fallback="logs")
    
    # Setup logger now that LOG_PATH is known
    series_slug = SERIES_NAME.lower().replace(" ", "_").replace("'", "")
    setup_logger(series_slug, LOG_PATH)
    logger.info(f"Loaded configuration from: {config_path}")

    found_series_config = False
    for i in range(1, 50): # Iterate through potential series configurations
        series_key = f"series_name_{i}"
        # Corrected: Use 'series' section name
        if config_parser.has_option("series", series_key) and \
           config_parser.get("series", series_key).strip('"') == series_name:
            
            # Corrected: Use 'series' section name
            ROOT_FOLDER = config_parser.get("series", f"series_path_{i}", fallback="")
            
            # Construct metadata and output JSON paths within series-specific subfolders
            METADATA_JSON = os.path.join(JSON_FOLDER, series_slug, f"{series_name}.json")
            OUTPUT_JSON = os.path.join(JSON_FOLDER, series_slug, f"{series_name.replace(' ', '_')}_Processed.json")
            
            # Corrected: Use 'thresholds' section name
            PASS4_THRESHOLD = int(config_parser.get("thresholds", f"pass4_threshold_{series_slug}", fallback="12"))
            PASS2_THRESHOLD = float(config_parser.get("thresholds", f"pass2_threshold_{series_slug}", fallback="0.80"))
            PASS3_THRESHOLD = float(config_parser.get("thresholds", f"pass3_threshold_{series_slug}", fallback="0.80"))
            
            found_series_config = True
            logger.info(f"Configuration loaded for series '{series_name}':")
            logger.info(f"  ROOT_FOLDER: {ROOT_FOLDER}")
            logger.info(f"  METADATA_JSON: {METADATA_JSON}")
            logger.info(f"  OUTPUT_JSON: {OUTPUT_JSON}")
            logger.info(f"  PASS2_THRESHOLD: {PASS2_THRESHOLD}")
            logger.info(f"  PASS3_THRESHOLD: {PASS3_THRESHOLD}")
            logger.info(f"  PASS4_THRESHOLD: {PASS4_THRESHOLD}")
            return

    if not found_series_config:
        logger.error(f"Series name '{series_name}' not found in 'series' section of paths.txt.")
        raise ValueError(f"Series name '{series_name}' not found in paths.txt.")

# ------------------
# Local File Scanning
# ------------------

def scan_xml_metadata() -> dict:
    """
    Scans the ROOT_FOLDER for .xml files (NextPVR EPG metadata).
    Groups XML files by their normalized subtitle and description.
    Returns a dictionary where keys are (normalized_subtitle, normalized_description) tuples
    and values are lists of corresponding XML filenames.
    """
    epg_groups = defaultdict(list)
    logger.info(f"Scanning XML metadata in: {ROOT_FOLDER}")
    for file in os.listdir(ROOT_FOLDER):
        if file.endswith(".xml") and os.path.getsize(os.path.join(ROOT_FOLDER, file)) > 0:
            full_path = os.path.join(ROOT_FOLDER, file)
            try:
                tree = ET.parse(full_path)
                root = tree.getroot()
                subtitle = root.findtext("subtitle", "")
                description = root.findtext("description", "")
                
                # Normalize for consistent grouping
                normalized_subtitle = normalize(subtitle)
                normalized_description = normalize(description)
                
                key = (normalized_subtitle, normalized_description)
                epg_groups[key].append(file)
                logger.debug(f"Scanned XML: {file}, subtitle='{normalized_subtitle[:50]}...', description='{normalized_description[:50]}...'")
            except ET.ParseError as e:
                logger.warning(f"XML Parse Error: {file} - {e}. Skipping file.")
            except Exception as e:
                logger.error(f"Error scanning XML file {file}: {e}", exc_info=True)
    logger.info(f"Found {len(epg_groups)} unique XML subtitle/description groups.")
    return epg_groups

def find_related_ts_files(xml_basenames: set) -> dict:
    """
    Scans the ROOT_FOLDER for .ts files and groups them by their base filename.
    Only includes .ts files that have a corresponding .xml file (or a variation like -0.xml).
    Returns a dictionary where keys are base filenames (without extension) and values
    are lists of dictionaries containing path, size, and broken status for .ts files.
    """
    groups = defaultdict(list)
    logger.info(f"Finding related .ts files in: {ROOT_FOLDER}")
    for file in os.listdir(ROOT_FOLDER):
        if not file.endswith(".ts"):
            continue
        
        # Extract base filename, handling potential '-0' for broken recordings
        base = re.sub(r"(-0)+(?=\.ts$)", "", file[:-3]) # Remove .ts and '-0' if present
        full_path = os.path.join(ROOT_FOLDER, file)
        
        # Check if a corresponding XML file exists for this base
        # This ensures we only process .ts files that have associated EPG data
        if (base + ".xml" in xml_basenames or 
            any((base + s + ".xml") in xml_basenames for s in ["-0", "-0-0"])): # Check for common XML variations
            
            groups[base].append({
                "path": full_path.replace("\\", "/"), # Standardize path separators
                "size": os.path.getsize(full_path),
                "broken": "-0" in file # Flag if it's a broken recording based on filename
            })
            logger.debug(f"Found related .ts file: {file} for basename {base}")
    logger.info(f"Found {len(groups)} groups of related .ts files.")
    return groups

# ------------------
# Provider Metadata Processing
# ------------------

def load_series_metadata() -> dict:
    """
    Loads the comprehensive series metadata JSON generated by Season_Episode_builder.py.
    This JSON contains all seasons and episodes with data from various providers.
    """
    if not os.path.exists(METADATA_JSON):
        logger.error(f"Metadata JSON file not found: {METADATA_JSON}. Please run Season_Episode_builder.py first.")
        raise FileNotFoundError(f"Metadata JSON not found: {METADATA_JSON}")
    
    logger.info(f"Loading series metadata from: {METADATA_JSON}")
    try:
        with open(METADATA_JSON, "r", encoding="utf-8") as f:
            metadata = json.load(f)
        logger.info("Series metadata loaded successfully.")
        return metadata
    except json.JSONDecodeError as e:
        logger.error(f"Error decoding metadata JSON from {METADATA_JSON}: {e}", exc_info=True)
        raise
    except Exception as e:
        logger.error(f"Error loading series metadata from {METADATA_JSON}: {e}", exc_info=True)
        raise

def build_match_pool(meta: dict) -> list:
    """
    Builds a pool of episodes from the loaded series metadata for matching.
    Each entry in the pool contains normalized titles and overviews from all providers.
    This pool is what the matching passes will iterate through.
    """
    pool = []
    seen_keys = set() # To track (season, episode) tuples to prevent duplicates in the pool

    logger.info("Building match pool from provider metadata.")
    for season in meta.get("seasons", []):
        season_num = season.get("season_number")
        if season_num is None:
            logger.warning(f"Skipping season in metadata with missing 'season_number': {season}")
            continue

        for ep in season.get("episodes", []):
            episode_num = ep.get("episode_number")
            if episode_num is None:
                logger.warning(f"Skipping episode in metadata with missing 'episode_number': S{season_num} - {ep}")
                continue

            # Create a unique key for the episode (season, episode_number)
            # Handle string episode numbers like "null_1" for season 0 by keeping them as strings
            ep_key = (season_num, str(episode_num)) 
            
            if ep_key in seen_keys:
                logger.warning(f"Duplicate episode key found in provider metadata: S{season_num}E{episode_num}. Skipping duplicate entry for match pool.")
                continue
            seen_keys.add(ep_key)

            # Collect all normalized titles from the 'titles' dictionary
            # Filter out empty strings and titles that might indicate generic "Episode" names
            normalized_titles = [
                normalize(t) for t in ep.get("titles", {}).values() 
                if t and "episode" not in t.lower() # Exclude generic "Episode" titles
            ]
            
            # Collect all normalized overviews from the 'overviews' dictionary
            normalized_overviews = [
                normalize(o) for o in ep.get("overviews", {}).values() if o
            ]

            pool.append({
                "season": season_num,
                "episode": episode_num,
                "titles": normalized_titles, # List of normalized titles from all providers
                "overviews": normalized_overviews, # List of normalized overviews from all providers
                "original_title": ep.get("titles", {}).get("tvmaze", ""), # Store a preferred original title for display/logging
                "air_date": ep.get("air_date", {}).get("tvmaze", "") # Store a preferred air_date for display/logging
            })
            logger.debug(f"Added to match pool: S{season_num}E{episode_num}, titles={normalized_titles[:3]}, overviews={normalized_overviews[:1]}")
    logger.info(f"Match pool built with {len(pool)} entries.")
    return pool

# ------------------
# Matching Logic
# ------------------

def slide_window(text: str, size: int = 10) -> list:
    """
    Generates sliding window snippets from a given text.
    Used for Pass 3 to find matches within longer descriptions.
    """
    words = text.split()
    return [' '.join(words[i:i+size]) for i in range(len(words) - size + 1)]

def token_overlap(text1: str, text2: str) -> int:
    """
    Calculates the number of overlapping unique tokens (words) between two texts.
    Used for Pass 4 for a different type of description similarity.
    """
    set1 = set(text1.split())
    set2 = set(text2.split())
    return len(set1.intersection(set2))

def match_group_to_provider(subtitle: str, desc: str, match_pool: list, pass_num: int):
    """
    Attempts to match a local XML subtitle/description pair to an episode in the match_pool
    using a multi-pass strategy.
    Returns the index of the matched episode in the pool and the matched episode dictionary,
    or (None, None) if no match is found.
    """
    logger.debug(f"Pass {pass_num}: Processing local subtitle='{subtitle}', pool size={len(match_pool)}")
    
    key_sub = normalize(subtitle)
    key_desc = normalize(desc)
    words_in_desc = key_desc.split()

    # Pass 1: Exact Subtitle Match (with tvmaze preference)
    if pass_num == 1:
        for i, m in enumerate(match_pool):
            # Prioritize matching against the 'original_title' (which is tvmaze's title)
            if m["original_title"] and key_sub == normalize(m["original_title"]):
                logger.info(f"Pass 1: Matched subtitle='{key_sub}' to TVMaze title='{m['original_title']}', S{m['season']}E{m['episode']}")
                return i, m
            # Then check all other normalized titles
            if key_sub in m["titles"]:
                logger.info(f"Pass 1: Matched subtitle='{key_sub}' to title in pool, S{m['season']}E{m['episode']}")
                return i, m
        logger.debug(f"Pass 1: No exact match for subtitle='{key_sub}'")
        return None, None

    # Pass 2: Fuzzy Subtitle Match
    elif pass_num == 2:
        for i, m in enumerate(match_pool):
            # Check against all normalized titles in the pool entry
            for title_in_pool in m["titles"]:
                if title_in_pool and SequenceMatcher(None, key_sub, title_in_pool).ratio() >= PASS2_THRESHOLD:
                    logger.info(f"Pass 2: Matched subtitle='{key_sub}' to '{title_in_pool}', S{m['season']}E{m['episode']} (ratio={SequenceMatcher(None, key_sub, title_in_pool).ratio():.2f})")
                    return i, m
        logger.debug(f"Pass 2: No fuzzy subtitle match for '{key_sub}' (threshold={PASS2_THRESHOLD})")
        return None, None

    # Pass 3: Sliding Window Description Match
    elif pass_num == 3 and len(words_in_desc) >= 10: # Only run if description is long enough for snippets
        snippets = slide_window(key_desc)
        for i, m in enumerate(match_pool):
            for overview_in_pool in m["overviews"]:
                for snippet in snippets:
                    ratio = SequenceMatcher(None, snippet, overview_in_pool).ratio()
                    if ratio >= PASS3_THRESHOLD:
                        logger.info(f"Pass 3: Matched snippet='{snippet[:30]}...' to overview='{overview_in_pool[:30]}...', S{m['season']}E{m['episode']} (ratio={ratio:.2f})")
                        return i, m
        logger.debug(f"Pass 3: No sliding window match for description='{key_desc[:50]}...' (threshold={PASS3_THRESHOLD})")
        return None, None

    # Pass 4: Token Overlap Description Match with Subtitle Ratio Check
    elif pass_num == 4:
        for i, m in enumerate(match_pool):
            for overview_in_pool in m["overviews"]:
                overlap = token_overlap(key_desc, overview_in_pool)
                if overlap >= PASS4_THRESHOLD:
                    # Additional check: ensure subtitle similarity is not too low
                    max_subtitle_ratio = 0
                    if m["titles"]:
                        max_subtitle_ratio = max([SequenceMatcher(None, key_sub, t).ratio() for t in m["titles"]])

                    # Stricter rules for Season 0 (specials) matches
                    if m["season"] == 0:
                        if max_subtitle_ratio < 0.90: # Require very high subtitle match for specials
                            logger.debug(f"Pass 4: Rejected Season 0 match for '{key_sub}' (S{m['season']}E{m['episode']}) due to low subtitle ratio ({max_subtitle_ratio:.2f})")
                            continue
                    elif max_subtitle_ratio < 0.60: # General subtitle match threshold for non-specials
                        logger.debug(f"Pass 4: Rejected match for '{key_sub}' (S{m['season']}E{m['episode']}) due to low subtitle ratio ({max_subtitle_ratio:.2f})")
                        continue
                    
                    logger.info(f"Pass 4: Matched description='{key_desc[:50]}...' to overview='{overview_in_pool[:50]}...', S{m['season']}E{m['episode']} (overlap={overlap}, subtitle_ratio={max_subtitle_ratio:.2f})")
                    return i, m
        logger.debug(f"Pass 4: No token overlap match for description='{key_desc[:50]}...' (threshold={PASS4_THRESHOLD})")
        return None, None

    logger.info(f"Final: No match found after all passes for subtitle='{key_sub}', description='{key_desc[:50]}...'")
    return None, None

def build_episode_groups() -> dict:
    """
    Orchestrates the crawling, metadata loading, and matching process.
    Produces the final structured JSON output mapping local files to matched episodes.
    """
    epg_data = scan_xml_metadata() # Local XML data grouped by (subtitle, description)
    provider_meta = load_series_metadata() # Comprehensive metadata from Season_Episode_builder.py
    match_pool = build_match_pool(provider_meta) # Pool of episodes from provider metadata for matching

    results = {"series_name": SERIES_NAME, "seasons": []}
    
    # Collect all unique XML basenames to find related .ts files
    all_xml_basenames = set(os.path.splitext(f)[0] for group_list in epg_data.values() for f in group_list)
    ts_groups = find_related_ts_files(all_xml_basenames)

    # Convert epg_data (dict) to a list of (subtitle, desc, xml_list) tuples for iteration
    # This list will be reduced as matches are found.
    unmatched_epg_pairs = [(subtitle, desc, xml_list) for (subtitle, desc), xml_list in epg_data.items()]
    
    # Store matched results temporarily before structuring into seasons
    temp_matched_episodes = defaultdict(list) # Key: (season_num, episode_num), Value: list of matched group dicts
    
    # Store unmatched local files
    unmatched_local_files_data = []

    logger.info(f"Starting matching process with {len(unmatched_epg_pairs)} local EPG pairs and {len(match_pool)} provider episodes.")

    # Iterate through matching passes
    for pass_num in range(1, 5):
        logger.info(f"--- Starting Pass {pass_num} ---")
        current_pass_unmatched = [] # Pairs that remain unmatched in this pass
        
        # Create a copy of the match_pool for this pass if it's Pass 3 or 4
        # This is because Pass 3 and 4 don't pop items, and we need to ensure they see the full remaining pool.
        current_match_pool_for_pass = match_pool[:] # Use a slice to create a shallow copy

        for subtitle, desc, xml_list in unmatched_epg_pairs:
            # Attempt to match the current local XML group to an episode in the pool
            index, matched_provider_episode = match_group_to_provider(subtitle, desc, current_match_pool_for_pass, pass_num)
            
            if matched_provider_episode and index is not None:
                # A match was found!
                logger.info(f"Match found in Pass {pass_num}: Local '{subtitle[:50]}...' matched to S{matched_provider_episode['season']}E{matched_provider_episode['episode']} ('{matched_provider_episode['original_title']}')")
                
                # Construct the group data for this matched episode
                group_data = {
                    "local_xml_subtitle": subtitle,
                    "local_xml_description": desc,
                    "matched_season": matched_provider_episode["season"],
                    "matched_episode": matched_provider_episode["episode"],
                    "matched_by_pass": pass_num,
                    # Include the full provider metadata for the matched episode
                    "provider_metadata": {
                        "titles": matched_provider_episode["titles"],
                        "overviews": matched_provider_episode["overviews"],
                        "ids": matched_provider_episode.get("ids", {}), # Ensure 'ids' is present, even if empty
                        "air_date": matched_provider_episode.get("air_date", {}), # Ensure 'air_date' is present
                        "synthetic": matched_provider_episode.get("synthetic", False) # Include synthetic flag
                    },
                    "files": [] # List of associated .ts files and their info
                }

                # Add associated .ts files to this group
                for xml_file in xml_list:
                    basename = os.path.splitext(xml_file)[0]
                    related_ts = ts_groups.get(basename, [])
                    if related_ts:
                        group_data["files"].extend(related_ts)
                    else:
                        # If no .ts file was found for this XML basename, add a placeholder
                        group_data["files"].append({
                            "path": os.path.join(ROOT_FOLDER, f"{basename}.ts").replace("\\", "/"),
                            "size": 0,
                            "broken": False,
                            "note": "No .ts file found for this XML basename"
                        })
                
                # Add this matched group to our temporary storage
                temp_matched_episodes[(matched_provider_episode["season"], matched_provider_episode["episode"])].append(group_data)
                
                # Remove the matched item from the pool to prevent re-matching in subsequent passes
                # For Pass 3 and 4, we need to remove from the original match_pool, not the copy.
                # This requires finding the original index in the main match_pool.
                if matched_provider_episode in match_pool: # Check if it's still there
                    match_pool.remove(matched_provider_episode)
                    logger.debug(f"Removed S{matched_provider_episode['season']}E{matched_provider_episode['episode']} from match_pool. New size: {len(match_pool)}")
                else:
                    logger.debug(f"S{matched_provider_episode['season']}E{matched_provider_episode['episode']} already removed from match_pool.")

            else:
                # No match found in this pass, keep for the next pass
                current_pass_unmatched.append((subtitle, desc, xml_list))
        
        unmatched_epg_pairs = current_pass_unmatched # Update the list of unmatched pairs for the next pass
        logger.info(f"Pass {pass_num} completed. {len(unmatched_epg_pairs)} pairs remaining unmatched.")
        
        if not unmatched_epg_pairs: # If all matched, no need for further passes
            logger.info("All local EPG pairs matched. Ending matching process early.")
            break

    # --- Finalize Results ---
    # Structure the matched episodes into seasons
    for (season_num, episode_num), matched_groups in temp_matched_episodes.items():
        # Find or create the season in the final results structure
        target_season = next((s for s in results["seasons"] if s["season_number"] == season_num), None)
        if not target_season:
            target_season = {"season_number": season_num, "episodes": []}
            results["seasons"].append(target_season)
        
        # Each unique (season, episode) from provider metadata should have one entry.
        # If multiple local XMLs matched the same provider episode, they will be grouped here.
        # For simplicity, we'll just take the first matched group's metadata for the episode entry,
        # but all associated files will be included.
        
        # The 'provider_metadata' within the group_data already contains the full nested dictionaries.
        # We need to extract that and add it to the season's episodes list.
        
        # Assuming there's at least one matched group for this (season, episode)
        first_group = matched_groups[0]
        episode_entry = {
            "episode_number": episode_num,
            "local_xml_subtitle": first_group["local_xml_subtitle"],
            "local_xml_description": first_group["local_xml_description"],
            "matched_by_pass": first_group["matched_by_pass"],
            "titles": first_group["provider_metadata"]["titles"],
            "overviews": first_group["provider_metadata"]["overviews"],
            "ids": first_group["provider_metadata"]["ids"],
            "air_date": first_group["provider_metadata"]["air_date"],
            "synthetic": first_group["provider_metadata"].get("synthetic", False),
            "files": [] # All files for this unique provider episode
        }
        
        # Consolidate all files from all local XMLs that matched this provider episode
        for group in matched_groups:
            episode_entry["files"].extend(group["files"])
        
        target_season["episodes"].append(episode_entry)

    # Sort seasons and episodes for consistent output
    results["seasons"].sort(key=lambda x: x["season_number"])
    for season in results["seasons"]:
        season["episodes"].sort(key=lambda x: x["episode_number"])

    # Handle any remaining unmatched local EPG pairs
    if unmatched_epg_pairs:
        logger.info(f"Found {len(unmatched_epg_pairs)} local EPG pairs that could not be matched to provider metadata.")
        unmatched_season = {"season_number": "unmatched", "episodes": []} # Use a string for 'unmatched' season
        
        # Assign sequential 'episode' numbers for unmatched items for display purposes
        unmatched_episode_counter = 1
        for subtitle, desc, xml_list in unmatched_epg_pairs:
            unmatched_entry = {
                "episode_number": unmatched_episode_counter, # Sequential number for unmatched
                "local_xml_subtitle": subtitle,
                "local_xml_description": desc,
                "files": [],
                "reason": "No match found in provider metadata"
            }
            # Add associated .ts files
            for xml_file in xml_list:
                basename = os.path.splitext(xml_file)[0]
                related_ts = ts_groups.get(basename, [])
                if related_ts:
                    unmatched_entry["files"].extend(related_ts)
                else:
                    # If no .ts file was found for this XML basename, add a placeholder
                    unmatched_entry["files"].append({
                        "path": os.path.join(ROOT_FOLDER, f"{basename}.ts").replace("\\", "/"),
                        "size": 0,
                        "broken": False,
                        "note": "No .ts file found for this XML basename"
                    })
            unmatched_season["episodes"].append(unmatched_entry)
            unmatched_episode_counter += 1
        
        results["seasons"].append(unmatched_season) # Add the unmatched season to results
        results["seasons"].sort(key=lambda x: x["season_number"] if isinstance(x["season_number"], int) else float('inf')) # Sort to put 'unmatched' at the end

    logger.info(f"Matching process complete. Total seasons in output: {len(results['seasons'])}")
    return results

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python scripts/series_folder_crawler.py \"Series Name\"")
        sys.exit(1)

    SERIES_NAME_ARG = sys.argv[1] # Use a temporary variable for the argument
    
    # Initialize logger before loading paths to catch potential errors during path loading
    # This requires a temporary slug, which will be refined in load_paths
    temp_series_slug = SERIES_NAME_ARG.lower().replace(" ", "_").replace("'", "")
    setup_logger(temp_series_slug, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "logs")) # Default log path

    try:
        load_paths(SERIES_NAME_ARG) # This will re-initialize the logger with the correct path
        grouped = build_episode_groups()
        
        # Ensure the output directory exists before writing
        output_dir = os.path.dirname(OUTPUT_JSON)
        os.makedirs(output_dir, exist_ok=True)

        with open(OUTPUT_JSON, "w", encoding="utf-8") as f:
            json.dump(grouped, f, indent=2)
        logger.info(f"Finished. Output saved to {OUTPUT_JSON}")
    except Exception as e:
        logger.exception(f"An unhandled error occurred during script execution for '{SERIES_NAME_ARG}': {e}")
        sys.exit(1)

